# Loads the AFINN-111 lexicon (Finn Årup Nielsen, ODbL v1.0)
# See README for full attribution.


#Source: Claude opus 5
#function: locate file path for databases when running on web
import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))

def data_path(name):
    return os.path.join(BASE_DIR, "data", name)
#end of code generated by claude

def load_AFINN():
    lexicon = {}
    with open(data_path("AFINN-111.txt")) as f:
        for line in f:
            word,score = line.split("\t")
            lexicon[word] = int(score)
    return lexicon

def load_rhetoric_words():
    words = set()
    with open(data_path("rhetoric_words.txt")) as f:
        for line in f:
            word = line.strip().lower()
            if word:
                words.add(word)
    return words

def load_excluded_words():
    words = set()
    with open(data_path("excluded_from_repetition.txt")) as f:
        for line in f:
            word = line.strip().lower()
            if word:
                words.add(word)
    return words